# Generated by Django 5.0.1 on 2024-04-27 04:37

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_time', models.DateTimeField()),
                ('event_time', models.DateTimeField()),
                ('last_updated_time', models.DateTimeField()),
                ('booking_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('AUTOMATICALLY_DECLINED', 'Automatically Declined')], default='PENDING', max_length=60)),
                ('booking_type', models.CharField(choices=[('ACADEMIC', 'Academic'), ('WORKSHOP', 'Workshop'), ('EVENT', 'Event'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('event_duration', models.IntegerField()),
                ('expected_strength', models.IntegerField()),
                ('title', models.TextField(default='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('building_picture', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('parent', models.EmailField(max_length=200, null=True)),
                ('require_parent_permission', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField()),
                ('is_authority', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_time', models.DateTimeField()),
                ('comment_content', models.TextField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbs_app.booking')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vbs_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_status', models.CharField(choices=[('PENDING_RECEIVE', 'Receive Pending'), ('RECEIVED', 'Received'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled'), ('AUTOMATICALLY_DECLINED', 'Automatically Declined')], default='PENDING_RECEIVE', max_length=60)),
                ('last_updated_time', models.DateTimeField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbs_app.booking')),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbs_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbs_app.user'),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('floor_number', models.IntegerField()),
                ('venue_type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('LAB', 'Lab'), ('MEETING_ROOM', 'Meeting Room'), ('AUDITORIUM', 'Auditorium'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('is_accessible', models.BooleanField()),
                ('seating_capacity', models.IntegerField()),
                ('has_air_conditioner', models.BooleanField()),
                ('has_projectors', models.BooleanField()),
                ('has_speakers', models.BooleanField()),
                ('has_whiteboard', models.BooleanField()),
                ('authority_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vbs_app.user')),
                ('building_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vbs_app.building')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='venue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbs_app.venue'),
        ),
        migrations.CreateModel(
            name='VHBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_time', models.DateTimeField()),
                ('last_updated_time', models.DateTimeField()),
                ('user_address', models.TextField()),
                ('user_contact', models.CharField(max_length=10)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('rooms_required', models.IntegerField()),
                ('booking_purpose', models.TextField()),
                ('booking_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('AUTOMATICALLY_DECLINED', 'Automatically Declined')], default='PENDING', max_length=60)),
                ('booking_type', models.CharField(choices=[('INSTITUTE_GUEST', 'Institute Guest'), ('OFFICIAL', 'Official'), ('PERSONAL', 'Personal')], default='PERSONAL', max_length=60)),
                ('requestby', models.CharField(choices=[('FACULTY', 'Faculty'), ('STAFF', 'Staff'), ('OFFICER', 'Officer'), ('STUDENT', 'Student'), ('ALUMNI', 'Alumni'), ('OTHER', 'Other')], default='OTHER', max_length=60)),
                ('id_proof', models.URLField(blank=True, null=True)),
                ('venues', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbs_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='VHBookingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_status', models.CharField(choices=[('PENDING_RECEIVE', 'Receive Pending'), ('RECEIVED', 'Received'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled'), ('AUTOMATICALLY_DECLINED', 'Automatically Declined')], default='PENDING_RECEIVE', max_length=60)),
                ('last_updated_time', models.DateTimeField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbs_app.vhbooking')),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbs_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='VHVenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('floor_number', models.IntegerField()),
                ('accomodation_type', models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('authority_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vbs_app.user')),
                ('building_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vbs_app.building')),
            ],
        ),
    ]
