# Generated by Django 5.0.1 on 2024-02-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vbs_app', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
