# Generated by Django 5.0.1 on 2024-04-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbs_app', '0003_remove_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
